# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2834155c53fbbd83405cc79ae076e1d7eec29bfefc4c2f7fed9e4292c3b1ae750ae83fdc2ec01160372001e796d2c3655cac1802698234c88b926edc502f926d

test:
  secret_key_base: 06d7a9c96d7a5ea3ef3ea4ef368812f97aed64b8f22cc865263ee2f45eb1926a4d126356af866e780693b6b1f649ed1b47ec3e21b32615663ae9ff36c70a00e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
